// Code generated by "stringer -type RegistryEvent -trimprefix RegistryEvent"; DO NOT EDIT.

package core

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RegistryEventRegistered-0]
	_ = x[RegistryEventUnregistered-1]
}

const _RegistryEvent_name = "RegisteredUnregistered"

var _RegistryEvent_index = [...]uint8{0, 10, 22}

func (i RegistryEvent) String() string {
	if i < 0 || i >= RegistryEvent(len(_RegistryEvent_index)-1) {
		return "RegistryEvent(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RegistryEvent_name[_RegistryEvent_index[i]:_RegistryEvent_index[i+1]]
}
